import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

type RouteContext = { params: Promise<{ projectId: string }> };

function isValidUuid(v: string) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
}

interface OutputSection {
  id: string;
  title: string;
  content: string;
  bullets?: string[];
  type: "text" | "bullets" | "slide";
}

/**
 * POST /api/studio/[projectId]/export?format=pptx|pdf
 *
 * PPT: Generates a real .pptx file using PptxGenJS.
 * PDF: Returns the output_json as structured HTML for client-side printing.
 */
export async function POST(request: NextRequest, ctx: RouteContext) {
  const { projectId } = await ctx.params;
  if (!isValidUuid(projectId)) {
    return NextResponse.json({ error: "Invalid project ID" }, { status: 400 });
  }

  const format = request.nextUrl.searchParams.get("format") ?? "pptx";
  if (!["pptx", "pdf"].includes(format)) {
    return NextResponse.json({ error: "format must be pptx or pdf" }, { status: 400 });
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: project, error } = await supabase
    .from("studio_projects")
    .select("*")
    .eq("project_id", projectId)
    .eq("user_id", user.id)
    .single();

  if (error || !project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  const sections: OutputSection[] = Array.isArray(project.output_json) ? project.output_json : [];

  if (format === "pdf") {
    // Return structured data for client-side print-to-PDF
    return NextResponse.json({ title: project.title, sections });
  }

  // === PPT generation via PptxGenJS ===
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();

  pptx.layout = "LAYOUT_WIDE";
  pptx.title = project.title;
  pptx.author = "RevSignal — The Strategist";

  // Theme colors
  const BG = "0D1117";
  const ACCENT = "6366F1"; // indigo accent-primary
  const TEXT_PRIMARY = "F1F5F9";
  const TEXT_MUTED = "94A3B8";

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: BG };
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: "100%",
    h: 0.08,
    fill: { color: ACCENT },
  });
  titleSlide.addText(project.title, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 1.5,
    fontSize: 36,
    bold: true,
    color: TEXT_PRIMARY,
    fontFace: "Inter",
    align: "left",
  });
  if (project.description) {
    titleSlide.addText(project.description, {
      x: 0.5,
      y: 3.2,
      w: 9,
      h: 1,
      fontSize: 16,
      color: TEXT_MUTED,
      fontFace: "Inter",
      align: "left",
    });
  }
  titleSlide.addText(`Generated by RevSignal · The Strategist`, {
    x: 0.5,
    y: 5.0,
    w: 9,
    h: 0.4,
    fontSize: 10,
    color: TEXT_MUTED,
    fontFace: "Inter",
    align: "left",
  });

  // Content slides
  for (const section of sections) {
    const slide = pptx.addSlide();
    slide.background = { color: BG };

    // Accent bar
    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 0.06,
      fill: { color: ACCENT },
    });

    // Section title
    slide.addText(section.title, {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.6,
      fontSize: 20,
      bold: true,
      color: TEXT_PRIMARY,
      fontFace: "Inter",
    });

    if (section.type === "bullets" && section.bullets && section.bullets.length > 0) {
      const bulletItems = section.bullets.map((b) => ({
        text: b,
        options: { bullet: { code: "2022" }, color: TEXT_PRIMARY, fontSize: 14 },
      }));
      slide.addText(bulletItems, {
        x: 0.5,
        y: 1.1,
        w: 9,
        h: 4,
        fontFace: "Inter",
        valign: "top",
      });
    } else {
      // Plain text — break into lines
      slide.addText(section.content, {
        x: 0.5,
        y: 1.1,
        w: 9,
        h: 4,
        fontSize: 14,
        color: TEXT_PRIMARY,
        fontFace: "Inter",
        valign: "top",
        wrap: true,
      });
    }
  }

  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;

  const safeName = project.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  return new NextResponse(new Uint8Array(buffer), {
    status: 200,
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${safeName}.pptx"`,
    },
  });
}
